global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "db-mysql"
    static_configs:
      - targets: ["exporter:9104"]

  - job_name: "mysql-node"
    static_configs:
      - targets: ["db-mysql:9100"]

  - job_name: "user"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user:8080"]

  - job_name: "review"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["review:8080"]

  - job_name: "place"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["place:8080"]

  - job_name: "nearspot"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["nearspot:8080"]

  - job_name: "bookmark"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["bookmark:8080"]

  - job_name: "user2"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["users:8080"]

  - job_name: "review2"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["reviews:8080"]

  - job_name: "place2"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["places:8080"]

  - job_name: "nearspot2"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["nearspots:8080"]

  - job_name: "bookmark2"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["bookmarks:8080"]
