version: "3"

services:
  db-mysql:
    image: mydb
    container_name: db-mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: trip
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 5080:3306
      - 9100:9100

  prom:
    image: prom
    container_name: prom
    ports:
      - 9090:9090
    depends_on:
      - db-mysql

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prom

  user:
    image: user
    container_name: user
    ports:
      - 5081:8080
    depends_on:
      - db-mysql

  review:
    image: review
    container_name: review
    ports:
      - 5082:8080
    depends_on:
      - db-mysql

  place:
    image: place
    container_name: place
    ports:
      - 5083:8080
    depends_on:
      - db-mysql

  nearspot:
    image: nearspot
    container_name: nearspot
    ports:
      - 5084:8080
    depends_on:
      - db-mysql

  bookmark:
    image: bookmark
    container_name: bookmark
    ports:
      - 5085:8080
    depends_on:
      - db-mysql

  users:
    image: user
    container_name: user2
    ports:
      - 5091:8080
    depends_on:
      - db-mysql

  reviews:
    image: review
    container_name: review2
    ports:
      - 5092:8080
    depends_on:
      - db-mysql

  places:
    image: place
    container_name: place2
    ports:
      - 5093:8080
    depends_on:
      - db-mysql

  nearspots:
    image: nearspot
    container_name: nearspot2
    ports:
      - 5094:8080
    depends_on:
      - db-mysql

  bookmarks:
    image: bookmark
    container_name: bookmark2
    ports:
      - 5095:8080
    depends_on:
      - db-mysql
