version: "3"

services:
  user:
    image: user
    container_name: user
    ports:
      - 5081:8080

  review:
    image: review
    container_name: review
    ports:
      - 5082:5002

  place:
    image: place
    container_name: place

  nearspot:
    image: nearspot
    container_name: nearspot
    ports:
      - 5084:5004

  bookmark:
    image: bookmark
    container_name: bookmark
    ports:
      - 5085:5005
