version: "3"

services:
  user:
    image: user
    container_name: user
    ports:
      - 5081:8080

  review:
    image: review
    container_name: review
    ports:
      - 5082:8080

  place:
    image: place
    container_name: place
    ports:
      - 5083:8080

  nearspot:
    image: nearspot
    container_name: nearspot
    ports:
      - 5084:8080

  bookmark:
    image: bookmark
    container_name: bookmark
    ports:
      - 5085:8080
